### ISSUE TITLE
Importing not functioning

### ISSUE THREAD

**Issue by TheManWhoLikesToCode** [benno094/pdf-anki#7]
When selecting add flashcard(s) to Anki, it says successfully imported. However, when checking my Anki deck after restarting and syncing, there are no decks or cards. I've added the add-on and added. Here's my config for add-on

{
    "apiKey": null,
    "apiLogPath": null,
    "ignoreOriginList": [],
    "webBindAddress": "127.0.0.1",
    "webBindPort": 8765,
    "webCorsOriginList": [
        "http://localhost",
        "https://pdf-anki.streamlit.app"
    ]
}

**Comment by benno094** [comment]
What OS and browser are you using?

**Comment by benno094** [comment]
I was able to replicate the issue by turning my ad/tracker-blocker on in Brave. Please try disabling that for the website.

Let me know if that fixes the issue, so I can close it.
