### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by iiONE** [benno094/pdf-anki#8]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://pdf-anki.streamlit.app/benno094/pdf-anki/main.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by benno094** [comment]
Thanks for the heads-up. I have a slight memory leak that I haven't got around to fixing. It lasts about a week before it crashes, then I usually reboot it straight away.
